### ISSUE TITLE
Criar ao banco de dados do ensaio SPT

### ISSUE THREAD

**Issue by icarob-eng** [Montaigne-ensaios/montaigne-android#2]
Criar banco de dados do ensaio SPT.
Estrutura:
- [x] Tabela de projetos: nome do projeto, id e nome da tabela de sondagens do projeto;
- [x] Tabela de sondagens: id/nome, profundidade;
- [x] Tabela desondagens, com dados de cada amostra: golpes 1, 2, 3 e nSPT;

**Comment by rodrigoCodDev** [comment]
O banco de dados está parcialmente pronto. 
Só precisamos resolver alguns pontos da estrutura dele e concluir a tabela de projetos SPT.

**Comment by rodrigoCodDev** [comment]
O banco está pronto, precisamos só checar possíveis erros e complementos para as classes relacionadas.
