### ISSUE TITLE
Criar reciclye da tela inicial e menu 

### ISSUE THREAD

**Issue by JuliaFreire** [Montaigne-ensaios/montaigne-android#20]
Criar um reciclye horizontal ,com ScrovView horizontal ,para tipos de ensaios exemplo :spt,proctor
Criar outro reciclye vertical com Scroview vertical para meus projetos .

Menu com: SOBRE NÓS (Não é tão necessario agr)

Menu do lado dos meus projetos com 
Excluir projeto
Adicionar projeto

**Comment by icarob-eng** [comment]
Duplicado de #14
