### ISSUE TITLE
ver como oculta ou edita o toolbar padrão

### ISSUE THREAD

**Issue by marmundo** [Montaigne-ensaios/montaigne-android#33]
@rodrigoCodDev

**Comment by rodrigoCodDev** [comment]
# Ocultar e editar Toolbar no Android Studio

Estes são os links que ache falando sobre o assunto:
[Como ocultar](https://youtu.be/2w5lfnueh7s)
[Como fazer menu da toolbar](https://youtu.be/e5_C9e_gKOM)
[Como customizar toolbar](https://youtu.be/2w5lfnueh7s)
