### ISSUE TITLE
Passar layouts do branch figma para integracao_java_ui

### ISSUE THREAD

**Issue by icarob-eng** [Montaigne-ensaios/montaigne-android#36]
Passar os layouts novos feitos no branch `figma` para o branch `integracao_java_ui`.
Layouts faltando:

- [x] `activity_spt_projeto2.xml`;
- [x] `activity_spt_editar2.xml`;
- [x] `activity_home1.xml`;
- [x] `activity_spt_criar1.xml`;
- [x] `activity_spt_criar_furo2.xml`;
- [x] `activity_app_sobre_nois.xml`;
- [x] `activity_gerenciar_proj_spt.xml`;
- [x] `activity_spt_carimbo_definitivo.xml`;
- [x] `activity_spt_carimbo_unico1.xml`;

Mais layouts poderão ser adicionados à essa issue caso necessário. Além de serem passados os arquivos, eles devem ser refatorados, e talvez refeitos, conforme a necessidade. Os recursos usasos pelos layouts serão vistos posteriormente.

**Comment by icarob-eng** [comment]
Existem 4 arquivos relativos ao carimbo: `activity_carimbo1.xml`, `activity_carimbo2.xml`, `activity_carimbo_definitivo.xml` e `activity_carimbo_unico1.xml`, embora o primeiro aparente ter sido apagado, tendo apenas o respectivo Java.

Também tive confusão relativa às activities de gerenciar projeto, havendo no branch figma `activity_spt_projeto2.xml`, `activity_spt_gerenciar_projs.xml` e `activity_gerenciar_proj_spt.xml`.

Por fim, o layout `activity_spt_criar1.xml` gera confusão em relação à `activity_spt_criar_furo2.xml`.

Tendo isso em vista, não sei como prosseguir nesta issue.

**Comment by JuliaFreire** [comment]
1-Os carimbos os unicos que devem permanecer são o carimbo unico e definitivo.
2-Sobre  a de gerencia é essa activy aqui que deve permanecer as outras podem ser descartadas activity_gerenciar_proj_spt.xml.
3- O layout que vai continuar é o activity_spt_criar1.xml .E a activity_spt_criar_furo2.xml (era para ser a do carimbo unico 2 portanto deve ser descartada).

obg:)

**Comment by icarob-eng** [comment]
Todos os layouts necessários foram transferidos. Apagando branch `figma`, `layout`, `SPT`, e juntado `integracao_java_ui` com o `dev`.
